-- Demo data for the whole system, loaded by `just seed`.
--
-- One file because there is one database. The gateway's own rows come first:
-- principals and budgets are what the control layer enforces against, and the
-- web fixtures below are meaningless without an identity to attribute them to.
--
-- Deterministic on purpose — the demo script depends on these exact slugs and
-- limits. Safe to re-run.

-- ========================= gateway: identities and limits ====================

insert into principals (slug, display_name, kind, allowed_models, allowed_tools, api_key_hash, role, delegates_users)
values
  -- A well-behaved agent with a narrow tool grant. It may read documents and
  -- query customer data, but not enumerate documents.
  ('demo-agent', 'Demo agent', 'agent',
   array['llama3.1:8b', 'qwen2.5:7b'],
   array['docs__read', 'docs__search', 'resources__describe', 'resources__query'],
   '191b558a694b9c5081fc238f779c811e6de37e92b1ca8471cb29ea96d4393a45', 'member', false),

  -- Broad model grant, one tool: used to show the tool grant doing the work
  -- rather than the controls. Grants are deny-by-default, so every model is
  -- listed explicitly.
  ('red-team', 'Red team harness', 'agent',
   array['llama3.1:8b', 'qwen2.5:7b', 'mistral:7b'],
   array['docs__search'],
   'febe127f44614453cda622de2c687f8e64435dace54cc0085deeb22cf9efa0cf', 'member', false),

  -- The console chat (GATEWAY_API_KEY): one key for every signed-in person,
  -- each named in `X-On-Behalf-Of`, so budgets, risk and activity are per
  -- user. Its tools are the resource tools; which tables, and which may be
  -- requested, is the catalog's `[resources]` call.
  ('console-chat', 'SecOps console chat', 'app',
   -- gpt-* are routed by the gateway to the console's OpenAI connection
   array['llama3.1:8b', 'qwen2.5:7b', 'gpt-5', 'gpt-5-mini'], array['resources__describe', 'resources__query'],
   'a9f5584b7e7fb03131d7d2887d521492591b1ad4fd9c88db49ae00686d4ba164', 'member', true),

  -- The self-test program (`just test system`). It names a fresh end user for
  -- every case, so its own refusals never add up to a risk block on anyone
  -- else, and holds one model and one tool so the grant refusals have
  -- something to refuse.
  ('selftest', 'Self-test harness', 'app',
   array['llama3.1:8b'], array['docs__read'],
   '91a0e47b3771253220cf8f6d9016d9ebd6c419d5e831df2be78445a2b14ae34d', 'member', true),

  -- The SecOps console's server-side identity (GATEWAY_ADMIN_KEY): streams and
  -- decides access requests. No models, no tools — it administers, never acts.
  ('secops-console', 'SecOps console', 'app', array[]::text[], array[]::text[],
   '943d28b8ad70296dff2b65fb4a17aaca0dffe92482b233100e4698390c1d89a0', 'security_admin', false)
on conflict (slug) do update
  set allowed_models  = excluded.allowed_models,
      allowed_tools   = excluded.allowed_tools,
      api_key_hash    = excluded.api_key_hash,
      role            = excluded.role,
      delegates_users = excluded.delegates_users;

-- Budgets are per user: a delegated end user, or an agent that acts for no
-- one under its own slug. Hard budgets refuse the call; soft ones record and
-- warn. A row may combine token, USD, request-count and concurrency limits;
-- the first one reached applies. Edited at runtime through the gateway's
-- PUT /admin/budgets.
insert into budgets (scope, scope_id, window_secs, limit_tokens, limit_usd, limit_requests, limit_concurrency, hard)
values
  ('global',    null,          86400, 2000000, 25.0, null, null, true),
  ('user',      'demo-agent',   3600,   50000, null, null,    4, true),
  ('user',      'red-team',     3600,   10000, null,  120, null, false)
on conflict (scope, coalesce(scope_id, '')) do update
  set window_secs       = excluded.window_secs,
      limit_tokens      = excluded.limit_tokens,
      limit_usd         = excluded.limit_usd,
      limit_requests    = excluded.limit_requests,
      limit_concurrency = excluded.limit_concurrency,
      hard              = excluded.hard;

-- The protected demo data in schema `resources` is generated by the
-- 20261004130000_resources_mcp migration, identically in every environment.

-- ============================ web: policies and incidents ===================

delete from public.incident_events;
delete from public.incidents;
delete from public.policies;

insert into public.policies (id, title, category, summary, body, status, version, review_due) values
  ('00000000-0000-4000-a000-000000000001', 'Password & MFA Policy', 'Access control',
   'All employees must use MFA and passwords of at least 14 characters.',
   E'1. MFA is mandatory for every company account.\n2. Minimum password length: 14 characters.\n3. Password reuse across services is prohibited.\n4. Use the company password manager.',
   'active', 3, current_date + 60),
  ('00000000-0000-4000-a000-000000000002', 'Acceptable Use of IT Assets', 'Acceptable use',
   'Rules for using company laptops, phones and network.',
   E'Company devices are for business use. No unapproved software. Report lost devices within 1 hour.',
   'active', 2, current_date + 120),
  ('00000000-0000-4000-a000-000000000003', 'Data Classification & Handling', 'Data protection',
   'Public / Internal / Confidential / Restricted classes and how to handle each.',
   E'Restricted data must never leave approved systems. Confidential data must be encrypted at rest and in transit.',
   'active', 1, current_date - 5),
  ('00000000-0000-4000-a000-000000000004', 'Incident Response Plan', 'Incident response',
   'Who does what when a security incident is detected.',
   E'Detect → Triage (15 min) → Contain → Eradicate → Recover → Post-mortem within 5 business days.',
   'active', 4, current_date + 200),
  ('00000000-0000-4000-a000-000000000005', 'Generative AI Usage', 'Acceptable use',
   'Which AI tools may be used and what data may be shared with them.',
   E'Only approved AI tools. Never paste Confidential or Restricted data into external AI services.',
   'draft', 1, null),
  ('00000000-0000-4000-a000-000000000006', 'Legacy VPN Access', 'Access control',
   'Superseded by Zero Trust Network Access policy.',
   E'Archived.', 'archived', 5, null);

insert into public.incidents (id, title, description, severity, status, category, source, policy_id, detected_at) values
  ('00000000-0000-4000-b000-000000000001', 'Phishing campaign targeting finance team',
   '14 employees received spoofed invoice emails; 2 clicked the link.', 'high', 'investigating',
   'Phishing', 'Email gateway', '00000000-0000-4000-a000-000000000001', now() - interval '3 hours'),
  ('00000000-0000-4000-b000-000000000002', 'Ransomware detected on build server',
   'EDR quarantined encryptor binary on build-03. Host isolated from network.', 'critical', 'contained',
   'Malware', 'EDR', '00000000-0000-4000-a000-000000000004', now() - interval '1 day'),
  ('00000000-0000-4000-b000-000000000003', 'Customer DB export shared via personal Drive',
   'DLP flagged a CSV with customer PII uploaded to a personal Google Drive.', 'high', 'open',
   'Data leak', 'DLP', '00000000-0000-4000-a000-000000000003', now() - interval '40 minutes'),
  ('00000000-0000-4000-b000-000000000004', 'Brute-force attempts on SSO',
   '3,200 failed logins from 12 IPs within 10 minutes. IPs blocked.', 'medium', 'resolved',
   'Account compromise', 'SIEM', '00000000-0000-4000-a000-000000000001', now() - interval '4 days'),
  ('00000000-0000-4000-b000-000000000005', 'Unapproved AI tool used with source code',
   'Proxy logs show uploads of repository archives to an unapproved AI service.', 'medium', 'open',
   'Policy violation', 'Web proxy', '00000000-0000-4000-a000-000000000005', now() - interval '6 hours'),
  ('00000000-0000-4000-b000-000000000006', 'Lost company laptop',
   'Employee reported laptop stolen from car. Disk encrypted; remote wipe issued.', 'low', 'resolved',
   'Lost device', 'Employee report', '00000000-0000-4000-a000-000000000002', now() - interval '9 days');

update public.incidents set resolved_at = detected_at + interval '5 hours' where status = 'resolved';

insert into public.incident_events (incident_id, kind, message, created_at) values
  ('00000000-0000-4000-b000-000000000001', 'note', 'Malicious sender domain blocked at gateway.', now() - interval '2 hours'),
  ('00000000-0000-4000-b000-000000000001', 'status', 'Status changed: open → investigating', now() - interval '2 hours'),
  ('00000000-0000-4000-b000-000000000002', 'note', 'build-03 isolated; snapshot taken for forensics.', now() - interval '23 hours'),
  ('00000000-0000-4000-b000-000000000002', 'status', 'Status changed: investigating → contained', now() - interval '20 hours');
