[package]
name = "gateway"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
arc-swap = "1.9.2"
axum.workspace = true
dotenvy.workspace = true
notify = "8.2.0"
regex = "1.13.1"
reqwest = { version = "0.13.5", default-features = false, features = ["json", "rustls"] }
serde.workspace = true
serde_json.workspace = true
sha2 = "0.11.0"
sqlx.workspace = true
thiserror = "2.0.21"
tokio.workspace = true
toml = "1.1.6"
tower-http = { version = "0.7.1", features = ["cors"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
uuid = { version = "1.27.0", features = ["serde", "v4"] }
